// Generated by CoffeeScript 1.6.3
(function() {
  var _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (window.app == null) {
    window.app = {
      currentFile: 'lesson32.zip'
    };
  }

  app.Browser = (function() {
    function _Class(page) {
      var _this = this;
      this.page = page;
      this.addItem = __bind(this.addItem, this);
      this.files = {};
      page.bind('pageshow', function(data) {
        return _this.enumerate();
      });
    }

    _Class.prototype.addFile = function(directory, filename, data) {
      var directoryName, slashPosition;
      if (filename === '') {
        return;
      }
      slashPosition = filename.indexOf('/');
      if (slashPosition !== -1) {
        directoryName = filename.substr(0, slashPosition + 1);
        filename = filename.substr(slashPosition + 1);
        if (!directory[directoryName]) {
          directory[directoryName] = {};
        }
        this.addFile(directory[directoryName], filename);
        return;
      }
      return directory[filename] = data;
    };

    _Class.prototype.addItem = function(name, path, data, isDir) {
      var element,
        _this = this;
      element = $('<li>').html("<a>" + name + "</a>");
      if (isDir) {
        element.bind('vclick', function() {
          return _this.showDirectory(path);
        });
      }
      this.page.find('ul').append(element).listview('refresh');
      return element;
    };

    _Class.prototype.showDirectory = function(dirname) {
      var data, directory, name, part, _i, _len, _ref;
      directory = this.files;
      if ((dirname != null ? dirname[0] : void 0) === '/') {
        dirname = dirname.slice(1);
      }
      if ((dirname != null ? dirname[dirname.length - 1] : void 0) === '/') {
        dirname = dirname.slice(0, dirname.length - 1);
      }
      if (dirname) {
        _ref = dirname.split('/');
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          part = _ref[_i];
          directory = directory[part + '/'];
        }
      } else {
        dirname = '';
      }
      this.page.find('ul').html('');
      if (dirname !== '') {
        this.addItem('..', '/' + dirname.slice(0, ('/' + dirname).lastIndexOf('/')), {}, true);
      }
      for (name in directory) {
        data = directory[name];
        this.addItem(name, "" + dirname + "/" + name, data, name.indexOf('/') !== -1);
      }
    };

    return _Class;

  })();

  app.FileBrowser = (function(_super) {
    __extends(FileBrowser, _super);

    function FileBrowser() {
      _ref = FileBrowser.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    FileBrowser.prototype.enumerate = function() {
      var browser, cursor, sdcard;
      sdcard = navigator.getDeviceStorage('sdcard');
      cursor = sdcard.enumerate();
      $('.ui-loading').show();
      browser = this;
      return cursor.onsuccess = function() {
        if (!this.result) {
          $('.ui-loading').hide();
          browser.showDirectory();
          return;
        }
        if (this.result.type === 'application/zip') {
          browser.addFile(browser.files, this.result.name, this.result);
        }
        this["continue"]();
      };
    };

    FileBrowser.prototype.addItem = function(name, path, data, isDir) {
      var element;
      element = FileBrowser.__super__.addItem.apply(this, arguments);
      if (!isDir) {
        return element.bind('vclick', function() {
          app.currentFile = path;
          return jQuery.mobile.changePage($('#zipbrowser'));
        });
      }
    };

    return FileBrowser;

  })(app.Browser);

  app.ZipBrowser = (function(_super) {
    __extends(ZipBrowser, _super);

    function ZipBrowser() {
      _ref1 = ZipBrowser.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    ZipBrowser.prototype.enumerate = function() {
      var browser, request, sdcard;
      sdcard = navigator.getDeviceStorage('sdcard');
      if (app.currentFile.indexOf('/') === 0) {
        app.currentFile = app.currentFile.slice(1);
      }
      console.log(app.currentFile);
      request = sdcard.get(app.currentFile);
      browser = this;
      request.onsuccess = function() {
        return zip.createReader(new zip.BlobReader(this.result), function(reader) {
          console.log(reader);
          return reader.getEntries(function(entries) {
            var entry, _i, _len;
            for (_i = 0, _len = entries.length; _i < _len; _i++) {
              entry = entries[_i];
              browser.addFile(browser.files, entry.filename, entry);
            }
            return browser.showDirectory();
          });
        });
      };
    };

    return ZipBrowser;

  })(app.Browser);

  $(document).bind('pageinit', function() {
    new app.FileBrowser($('#filebrowser'));
    return new app.ZipBrowser($('#zipbrowser'));
  });

}).call(this);
