// Generated by CoffeeScript 1.6.3
(function() {
  $(document).bind('pageinit', function() {
    var page;
    page = $('#filebrowser');
    return page.bind('pageshow', function() {
      var addFile, cursor, files, sdcard, showDirectory;
      files = {};
      addFile = function(directory, file) {
        var directoryName, slashPosition;
        if (!file.shortName) {
          file.shortName = file.name;
        }
        slashPosition = file.shortName.indexOf('/');
        if (slashPosition !== -1) {
          directoryName = file.shortName.substr(0, slashPosition);
          file.shortName = file.shortName.substr(slashPosition + 1);
          if (!directory[directoryName]) {
            directory[directoryName] = {};
          }
          addFile(directory[directoryName], file);
          return;
        }
        if (file.type === 'application/zip') {
          return directory[file.shortName] = file;
        }
      };
      showDirectory = function(dirname) {
        var addItem, data, directory, name, part, _i, _len, _ref;
        directory = files;
        if ((dirname != null ? dirname[0] : void 0) === '/') {
          dirname = dirname.slice(1);
        }
        if ((dirname != null ? dirname[dirname.length - 1] : void 0) === '/') {
          dirname = dirname.slice(0, dirname.length - 1);
        }
        if (dirname) {
          _ref = dirname.split('/');
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            part = _ref[_i];
            directory = directory[part];
          }
        } else {
          dirname = '';
        }
        page.find('ul').html('');
        addItem = function(name, path, isDir) {
          var element;
          element = $('<li>').html("<a>" + name + "</a>");
          if (isDir) {
            element.bind('vclick', function() {
              return showDirectory(path);
            });
          }
          return page.find('ul').append(element).listview('refresh');
        };
        if (dirname !== '') {
          addItem('..', '/' + dirname.slice(0, ('/' + dirname).lastIndexOf('/')), true);
        }
        for (name in directory) {
          data = directory[name];
          addItem(name, "" + dirname + "/" + name, !(data instanceof File));
        }
      };
      sdcard = navigator.getDeviceStorage('sdcard');
      cursor = sdcard.enumerate();
      $('.ui-loading').show();
      return cursor.onsuccess = function() {
        if (!this.result) {
          $('.ui-loading').hide();
          showDirectory();
          return;
        }
        addFile(files, this.result);
        return this["continue"]();
      };
    });
  });

}).call(this);
